package main

import (
	"fmt"
	"github.com/codeskyblue/go-sh"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
	"net/http"
)

func main() {
	//fmt.Println("hello")
	//for i, arg := range os.Args {
	//	fmt.Printf("arg[%d]='%s'\n", i, arg)
	//}

	baseDir := os.Args[1]

	out, err := exec.Command("ls", "-1", baseDir).Output()
	if err != nil {
		log.Fatal(err)
	}

	t := time.Now()
	currentDate := t.Format("2006-01-02")
	auditOutputDir := fmt.Sprintf("%s/Hashdeep/Hashdeep-Audit-%s", baseDir, currentDate)
	sh.Command("mkdir", auditOutputDir).Run()

	directories := strings.Split(string(out), "\n")
	for _, dir := range directories {
		// sh.Command("echo", dir).Run()
		logFile := fmt.Sprintf("%s/Hashdeep/Hashdeep-Logs/%s.txt", baseDir, dir)
		fullDirPath := fmt.Sprintf("%s/%s", baseDir, dir)
		auditOutputFile := fmt.Sprintf("%s/%s-Audit-%s.txt", auditOutputDir, dir, currentDate)
	//fmt.Println("audit output file:")
	//fmt.Println(auditOutputFile);		
		sh.Command("hashdeep", "-vv", "-a", "-k", logFile, "-r", fullDirPath).WriteStdout(auditOutputFile)
	}
	notify("hello you are my friend")

}
func notify(message string) {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
    bodyWithMessage := fmt.Sprintf("token=afkyay5x4p353ff4ahg34r223fs2oq&user=ujdxZUtT8n8ATCyJpDrHrQ93x6aGVS&message=%s", message)
	body := strings.NewReader(bodyWithMessage)

	req, err := http.NewRequest("POST", "https://api.pushover.net/1/messages.json", body)
	if err != nil {
		// handle err
	}
	req.SetBasicAuth("API_KEY", "")
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()

}
